name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate snake.svg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: athasyah
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
